final products = [
  {
    'id': 1,
    'title': 'Men\'s Nike Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image1.png',
    'brand': 'Nike',
  },
  {
    'id': 2,
    'title': 'Men\'s Nike Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image2.png',
    'brand': 'Nike',
  },
  {
    'id': 3,
    'title': 'Men\'s Adidas Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image3.png',
    'brand': 'Adidas',
  },
  {
    'id': 4,
    'title': 'Men\'s Nike Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image4.png',
    'brand': 'Nike',
  },
  {
    'id': 5,
    'title': 'Men\'s Bata Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image5.png',
    'brand': 'Bata',
  },
  {
    'id': 6,
    'title': 'Men\'s Bata Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image6.png',
    'brand': 'Bata',
  },
  {
    'id': 7,
    'title': 'Men\'s Nike Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image7.png',
    'brand': 'Nike',
  },
  {
    'id': 8,
    'title': 'Men\'s Adidas Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image8.png',
    'brand': 'Adidas',
  },
  {
    'id': 9,
    'title': 'Men\'s Bata Shoes',
    'price': '44.52',
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'assets/images/image9.png',
    'brand': 'Bata',
  }
];

final cart = [
  {
    'id': 6,
    'title': 'Men\'s Bata Shoes',
    'price': '44.52',
    'size': 8,
    'imageUrl': 'assets/images/image6.png',
    'brand': 'Bata',
  },
];
